name: assignment_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/roboto/static/  # Updated path for static fonts
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/static/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/static/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/static/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto/static/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/static/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/roboto/static/Roboto-MediumItalic.ttf
          style: italic
          weight: 500